version: '3.7'
services:

  db:
    container_name: db
    image: postgres:15rc1-alpine3.16
    volumes:
      - dbdata:/var/lib/postgresql/data
    env_file:
      - ./postgres.env
    ports:
      - "5432:5432"
    networks:
      eduright-network:
        ipv4_address: "172.12.0.2"

  backend:
    container_name: backend
    volumes:
      - staticfiles:/app/staticfiles
      - mediafiles:/app/media
    env_file:
      - ./postgres.env
      - ./backend.env
    build: ./backend
    ports:
      - "8080:8080"
    networks:
      eduright-network:
        ipv4_address: "172.12.0.4"

  nginx:
    container_name: nginx
    image: nginx:alpine
    volumes:
      - staticfiles:/static
      - mediafiles:/media
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    networks:
      eduright-network:
        ipv4_address: "172.12.0.3"
    depends_on:
      - backend

networks:
  eduright-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.12.0.0/16"

volumes:
    dbdata:
    staticfiles:
      name: staticfiles
    mediafiles:
      name: mediafiles