# Generated by Django 4.1.1 on 2022-10-01 04:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InfoTab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Just for identifying. Max Length is 50 characters.', max_length=50)),
                ('content', models.TextField()),
                ('icon', models.ImageField(blank=True, help_text='Min size should be 128x128, and try not to exceed maximum size>25kb.', null=True, upload_to='infotabsicons/', verbose_name='Imp Link Icon')),
                ('hide', models.BooleanField(default=False, help_text="Don't show this in the app.")),
                ('rank', models.IntegerField(default=0, help_text='The rank of class will signify the order at which, images will be displayed. Default is 0.')),
            ],
            options={
                'verbose_name': 'Information Tab',
                'verbose_name_plural': 'Information Tab',
                'ordering': ('rank',),
            },
        ),
        migrations.CreateModel(
            name='InternalPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Just for identifying. Max Length is 50 characters.', max_length=50)),
                ('link', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Max Length is 50 characters.', max_length=50)),
                ('url', models.URLField(help_text='Max Length is 250 characters.', max_length=250)),
                ('icon', models.ImageField(blank=True, help_text='Min size should be 128x128, and try not to exceed maximum size>25kb.', null=True, upload_to='impelinkicons/', verbose_name='Imp Link Icon')),
                ('rank', models.IntegerField(default=0, help_text='The rank of class will signify the order at which,  images will be displayed. Default is 0.')),
                ('hide', models.BooleanField(default=False, help_text="Don't show this in the app.")),
            ],
            options={
                'verbose_name': 'Link',
                'verbose_name_plural': 'Links',
                'ordering': ('rank',),
            },
        ),
        migrations.CreateModel(
            name='SlidingBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Just for identifying. Max Length is 50 characters.', max_length=50)),
                ('hide', models.BooleanField(default=False, help_text="Don't show this in the app.")),
                ('image', models.ImageField(blank=True, default='placeholder.png', help_text='Min size should be 534x300, and try not to exceed maximum size>25kb.', null=True, upload_to='homtabbanner/', verbose_name='Home Tab Banner Image')),
                ('plainShow', models.BooleanField(default=True, help_text='Whether the image just for show only.', verbose_name='Is for show')),
                ('is_Internal_Link', models.BooleanField(default=True, help_text='Whether the link leads to internal page of the app. If True fill the field below.')),
                ('is_External_Link', models.BooleanField(default=True, help_text='Whether the link leads to any external links. If True fill the field below.')),
                ('external_Link', models.URLField(blank=True, help_text='any link ex: https://www.youtube.com/watch?v=aHjpOzsQ9YI', max_length=250, null=True)),
                ('rank', models.IntegerField(default=0, help_text='The rank of class will signify the order at which, images will be displayed. Default is 0.')),
                ('slug', models.SlugField(unique=True)),
                ('internal_Page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.internalpage')),
            ],
            options={
                'verbose_name': 'Sliding Banner',
                'verbose_name_plural': 'Sliding Banners',
                'ordering': ('rank',),
            },
        ),
    ]
