# Generated by Django 3.2.4 on 2021-07-25 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('versioning', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='bugs',
            field=models.ManyToManyField(blank=True, to='versioning.Bugs'),
        ),
        migrations.AlterField(
            model_name='product',
            name='feature',
            field=models.ManyToManyField(blank=True, to='versioning.Feature'),
        ),
        migrations.AlterField(
            model_name='product',
            name='security',
            field=models.ManyToManyField(blank=True, to='versioning.Security'),
        ),
    ]
