# Generated by Django 3.2.4 on 2021-07-25 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('versioning', '0002_auto_20210725_0907'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='suports',
            field=models.CharField(blank=True, help_text='Supports Devices.', max_length=30, null=True),
        ),
    ]
