# Generated by Django 3.2.4 on 2021-07-26 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('versioning', '0004_rename_suports_product_supports'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='bugs',
            field=models.ManyToManyField(blank=True, null=True, to='versioning.Bugs'),
        ),
        migrations.AlterField(
            model_name='product',
            name='feature',
            field=models.ManyToManyField(blank=True, null=True, to='versioning.Feature'),
        ),
        migrations.AlterField(
            model_name='product',
            name='packages',
            field=models.ManyToManyField(blank=True, help_text='Packages included/removed.', null=True, to='versioning.Packages'),
        ),
        migrations.AlterField(
            model_name='product',
            name='security',
            field=models.ManyToManyField(blank=True, null=True, to='versioning.Security'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=30),
        ),
    ]
