# Generated by Django 3.2.4 on 2021-07-26 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('versioning', '0005_auto_20210726_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='bugs',
            field=models.ManyToManyField(blank=True, to='versioning.Bugs'),
        ),
        migrations.AlterField(
            model_name='product',
            name='feature',
            field=models.ManyToManyField(blank=True, to='versioning.Feature'),
        ),
        migrations.AlterField(
            model_name='product',
            name='packages',
            field=models.ManyToManyField(blank=True, help_text='Packages included/removed.', to='versioning.Packages'),
        ),
        migrations.AlterField(
            model_name='product',
            name='security',
            field=models.ManyToManyField(blank=True, to='versioning.Security'),
        ),
    ]
