# Generated by Django 3.2.4 on 2021-07-26 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('versioning', '0006_auto_20210726_1232'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feature',
            options={'ordering': ('-pending',)},
        ),
    ]
