# Generated by Django 4.1.1 on 2022-10-01 04:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FlashCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('front_Side_Text', models.TextField(blank=True, null=True)),
                ('front_Side_LateX', models.BooleanField(default=False, help_text='Whether the front side contain TeX format (default is "False").')),
                ('front_Side_Image', models.ImageField(blank=True, help_text='Min size should be 128x128, and try not to exceed maximum size>100kb.', null=True, upload_to='flashcard/', verbose_name='Flash Card Front Image')),
                ('front_image_Size', models.PositiveIntegerField(default=200, help_text='Size of the image content on size. (Default is 200[in px])')),
                ('back_Side_Text', models.TextField(blank=True, null=True)),
                ('back_Side_LateX', models.BooleanField(default=False, help_text='Whether the back side contain TeX format (default is "False").')),
                ('back_Side_Image', models.ImageField(blank=True, help_text='Min size should be 128x128, and try not to exceed maximum size>100kb.', null=True, upload_to='flashcard/', verbose_name='Flash Card Back Image')),
                ('back_image_Size', models.PositiveIntegerField(default=200, help_text='Size of the image content on size. (Default is 200[in px])')),
                ('date_Modified', models.DateField(auto_now=True)),
                ('likes', models.PositiveIntegerField(default=0)),
                ('datahash', models.CharField(blank=True, help_text='It will get calculated automatically', max_length=32, null=True)),
                ('rank', models.IntegerField(default=0, help_text='The rank of flashcards will signify the order at which, flashcards will be shown in list view. Ex. rank 0 will be up rank 4 will be down. Default is 0.')),
                ('added_By', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flashcardcreatedby', to=settings.AUTH_USER_MODEL)),
                ('liked_by', models.ManyToManyField(blank=True, related_name='likedby', to=settings.AUTH_USER_MODEL, verbose_name='Liked By')),
                ('modified_By', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flashcardmodifiedby', to=settings.AUTH_USER_MODEL)),
                ('topic', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='flashtopic', to='api.topics')),
            ],
        ),
    ]
