name: Edu Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    # runs-on: ubuntu-latest
    runs-on: edu-instance

    steps:
    - name: Setting Environment
      run: |
        echo "hello"
    