name: Edu Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: edu-instance

    # git action checkout
    steps:
      - uses: actions/checkout@v2

      - name: Save Environment Variables
        run: |
          echo "${{ secrets.POSTGRES_ENV }}" >> postgres.env
          echo "${{ secrets.DJANGO_ENV }}" >> backend.env
    
      - name: Build and Run Docker Containers
        run: |
          docker-compose up -d --build
