name: Edu Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: edu-instance

    # git action checkout
    steps:
      - uses: actions/checkout@v2

    